# -*- coding: utf-8 -*-
"""Student_Performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPNpxWh0b2dxHjxcq_4Ayh9wZyLrOecM

#    Student_Performance_ Analysis
"""

# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

from google.colab import files

uploaded = files.upload()

import os
print(os.listdir())

import zipfile

with zipfile.ZipFile('archive (9).zip', 'r') as zip_ref:
    zip_ref.extractall()

import os
print(os.listdir())

for file in os.listdir():
    if file.endswith('.csv'):
        print(file)

# Load Dataset
import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")

df

# Data Exploration
print("Rows and Columns:", df.shape)

df.columns

df.isnull()

# Data Types
df.info()

# Missing values
df.isnull().sum()

# Statistical analysis
df.describe()

# 5 Line Data Summary

# The dataset contains student demographic and academic information.

# It includes math, reading, and writing scores.

# The dataset contains categorical and numerical variables.

# No major missing values were found.

# The dataset is suitable for educational performance analysis.

"""# # Factor Analysis Questions"""

# Q1. Does parental education affect scores?
parent_score = df.groupby('parental level of education')[
    ['math score','reading score','writing score']
].mean()

print(parent_score.sort_values(by='math score', ascending=False))

### Observation

Students whose parents have a master's degree and bachelor's degree generally achieve
 the highest average scores. Students whose parents have only a high school education
 or some high school education tend to score lower. This suggests that parental education
 has a positive influence on student academic performance.

# Which race/ethnicity group has the highest average scores?
highest=df.groupby('race/ethnicity')[
       ['math score','reading score','writing score']].mean()
highest=highest.sort_values(by='math score',ascending=False)
print(highest)

# Q3. Correlation Between Subjects
correlation=df[
    ['math score','reading score','writing score']
].corr()
print(correlation)

### Observation

Reading and writing scores have a very strong positive correlation. Mathematics also has a strong positive relationship
with reading and writing, indicating that students performing well in one subject generally perform well in the others.

# Q4. Gender-wise Performance
performance =df.groupby('lunch')[
    ['math score','reading score','writing score']
    ].mean()
print(performance)

### Observation

Female students perform better in reading and writing,
 while male students slightly outperform female students in mathematics.
  Overall average scores are fairly similar between the two genders.

# Q5. Does lunch type affect performance?

lunch_performance=df.groupby('lunch')[
    ['math score','reading score','writing score']
].mean()

print(lunch_performance)

df["Total Score"] = df["math score"] + df["reading score"] + df["writing score"]

# What is the distribution of Total Scores?
df["Total Score"].describe()
print("Minimum Total Score :", df["Total Score"].min())
print("Maximum Total Score :", df["Total Score"].max())
print("Average Total Score :", round(df["Total Score"].mean(),2))
print("Median Total Score :", df["Total Score"].median())

### Observation

Most students scored around the average total score,
 while only a few students achieved extremely high or extremely low scores.
 The distribution indicates that the majority of students fall within the middle performance range.

"""# VISUALIZATION 1"""

# Parent Education vs Overall Score

# Parent Education
df['average_score']=(
    df['math score']+
     df['reading score']+
      df['writing score']
    )/3
parent_score=df.groupby('parental level of education')['average_score'].mean()
parent_score.sort_values(ascending=False)

# Overall Score
parent_score.sort_values().plot(
    kind='barh'
)
plt.title("Parent Education vs Overall Score")
plt.xlabel("Average Score")

plt.show()

"""# VISUALIZATION 2"""

# Is there a relationship between Math and Reading scores?
plt.figure(figsize=(10,6))
plt.scatter(df['math score'],df['reading score'])
plt.title('Math vs Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

"""# VISUALIZATION 3"""

# Correlation Heatmap
correlation=df[
    ['math score','reading score','writing score']
].corr()

plt.figure(figsize=(10,5))
sns.heatmap(
    correlation,
    annot=True,
    cmap='YlGnBu'
)

plt.title('Correlation heatmap')
plt.show()

"""# VISUALIZATION 4"""

# How do math scores vary across gender?
import matplotlib.pyplot as plt

variation=df.groupby('gender')['math score'].mean()
variation.plot(kind='bar')
plt.title('Variation between math scores across genders')
plt.xlabel('math score')
plt.ylabel('Gender')
plt.show()

"""# VISUALIZATION 5"""

# Which gender has the highest at-risk percentage?
at_risk=df[
     (df['reading score']<50)|
     (df['writing score']<50)|
     (df['math score']<50)
 ]

risk_count=at_risk['gender'].value_counts()
risk_gender=df['gender'].value_counts()

risk_percentage=(risk_count/risk_gender)*100
print(risk_percentage)

risk_count.plot(kind='bar')
plt.title('At-risk percentage by gender')
plt.ylabel("At-risk precentage")
plt.show()

"""# VISUALIZATION 6"""

# Classifying Students: High / Medium / Low Performers
df["average_score"] = df[["math score", "reading score", "writing score"]].mean(axis=1)

def performance_category(score):
    if score >= 75:
        return "High"
    elif score >= 50:
        return "Medium"
    else:
        return "Low"

df["performance"] = df["average_score"].apply(performance_category)

import matplotlib.pyplot as plt

df["performance"].value_counts().plot(kind="pie")

plt.title("Student Performance Classification")
plt.xlabel("Performance Level")
plt.ylabel("Number of Students")
plt.show()

"""# At Risk Segmentation

"""

# Define At-Risk Students
at_risk = df[
    (df["math score"] < 50) |
    (df["reading score"] < 50) |
    (df["writing score"] < 50)
]

at_risk.head()

# Total At-Risk Students
print("Total At-Risk Students:", len(at_risk))
print("Percentage:", round(len(at_risk)/len(df)*100,2), "%")

# At-Risk by Gender
at_risk.groupby("gender").size()

# At-Risk by Parental Education
at_risk.groupby("parental level of education").size()

# At-Risk by Lunch Type
at_risk.groupby("lunch").size()

# At-Risk Summary Table
risk_summary = pd.DataFrame({
    "Gender": at_risk["gender"].value_counts(),
    "Lunch": at_risk["lunch"].value_counts(),
    "Test Prep": at_risk["test preparation course"].value_counts()
})

risk_summary

"""# PRINCIPAL REPORT

"""

#  Principal’s Report

## Executive Summary
This analysis explores student performance in mathematics, reading, and writing. The goal is to identify factors influencing academic success and detect at-risk students.

## Key Findings
1. Test preparation significantly improves performance.
2. Parental education level impacts student scores.
3. Reading and writing are strongly correlated.
4. Female students perform better in reading and writing.
5. A notable percentage of students fall into the at-risk category.

## Recommendations
1. Introduce mandatory test preparation programs.
2. Provide extra support for at-risk students.
3. Increase parental involvement in academic activities.

## Reflection

The most impactful recommendation is implementing
structured test preparation programs. The analysis clearly
shows that students who completed test preparation performed better
across all subjects. Making this accessible to all students can significantly
improve overall academic performance and reduce the number of at-risk students.